// Curated weight configurations for common "what matters to me" personas.
// Missing module = use default weight (50). 0 = disable.

export const PRESETS = {
  "Retiree": {
    description: "Low taxes, warm weather, low disaster risk, cheap insurance.",
    weights: {
      cost_of_living: 80,
      income_tax: 90,
      sales_tax: 60,
      home_insurance: 80,
      disasters: 80,
      avg_temperature: 70,
      feels_like_temperature: 50,
      relative_humidity: 60,    // lower = drier = better for joints
      humidity: 60,
      sunshine_hours: 70,
      precipitation: 50,
      home_value: 70,
      median_rent: 70,
      price_per_sqft: 50,
      uv_index: 0,
      unemployment: 0,
      median_income: 0,
      public_lands: 30,
      gun_friendliness: 0,
      housing_inventory: 0,
      days_on_market: 0,
      median_sale_price: 60,
    },
  },

  "Remote Worker": {
    description: "Quality of life + affordable housing, jobs market doesn't matter as much.",
    weights: {
      cost_of_living: 70,
      median_rent: 80,
      home_value: 60,
      price_per_sqft: 60,
      income_tax: 70,
      sales_tax: 40,
      sunshine_hours: 60,
      avg_temperature: 50,
      feels_like_temperature: 40,
      relative_humidity: 50,
      humidity: 40,
      disasters: 60,
      public_lands: 50,
      unemployment: 0,
      median_income: 20,
      gun_friendliness: 0,
      median_sale_price: 40,
      uv_index: 0,
      home_insurance: 50,
    },
  },

  "Outdoors Enthusiast": {
    description: "Mountains, public land, sunshine. Population density doesn't matter.",
    weights: {
      public_lands: 100,
      sunshine_hours: 70,
      avg_temperature: 30,
      precipitation: 30,
      cost_of_living: 60,
      home_value: 50,
      median_rent: 40,
      uv_index: 20,
      disasters: 40,
      relative_humidity: 30,
      humidity: 30,
      income_tax: 30,
      gun_friendliness: 30,
      unemployment: 20,
      median_income: 0,
    },
  },

  "Family with Kids": {
    description: "Low cost, low crime/disaster risk, decent jobs market.",
    weights: {
      cost_of_living: 80,
      home_value: 90,
      median_rent: 70,
      price_per_sqft: 70,
      disasters: 90,
      unemployment: 60,
      median_income: 60,
      home_insurance: 70,
      income_tax: 50,
      sales_tax: 50,
      avg_temperature: 30,
      sunshine_hours: 40,
      relative_humidity: 20,
      humidity: 20,
      public_lands: 30,
      gun_friendliness: 0,
      median_sale_price: 80,
      housing_inventory: 40,
      days_on_market: 30,
      uv_index: 0,
    },
  },

  "Tax-Sensitive": {
    description: "Minimize all forms of tax exposure.",
    weights: {
      income_tax: 100,
      sales_tax: 90,
      home_insurance: 60,
      cost_of_living: 70,
      home_value: 50,
      median_rent: 40,
      disasters: 40,
      avg_temperature: 0,
      sunshine_hours: 0,
      relative_humidity: 0,
      humidity: 0,
      uv_index: 0,
      public_lands: 0,
      gun_friendliness: 0,
      median_income: 0,
      unemployment: 0,
      precipitation: 0,
      feels_like_temperature: 0,
      median_sale_price: 0,
      housing_inventory: 0,
      days_on_market: 0,
      price_per_sqft: 0,
    },
  },

  "Gun-Owner Libertarian": {
    description: "Permissive gun laws + outdoor land + low taxes.",
    weights: {
      gun_friendliness: 100,
      public_lands: 70,
      income_tax: 80,
      sales_tax: 60,
      cost_of_living: 60,
      home_value: 50,
      disasters: 40,
      sunshine_hours: 30,
      median_rent: 30,
      median_income: 0,
      unemployment: 0,
      humidity: 30,
      relative_humidity: 30,
      home_insurance: 40,
    },
  },

  "Young Professional": {
    description: "Career upside, city energy, rent that won't bankrupt you. Not your dad's preset.",
    weights: {
      median_income: 80,
      unemployment: 80,
      bachelors_pct: 80,
      median_rent: 90,
      population_density: 70,
      population: 60,
      broadband_pct: 70,
      cost_of_living: 60,
      commute_time: 60,
      median_age: 40,  // tilts toward states with younger populations
      disasters: 30,
      sunshine_hours: 30,
      home_value: 30,
      median_sale_price: 0,
      home_insurance: 20,
      income_tax: 30,
      gun_friendliness: 0,
      humidity: 0,
      uv_index: 0,
      public_lands: 0,
      avg_temperature: 0,
      feels_like_temperature: 0,
      precipitation: 0,
      housing_inventory: 0,
      days_on_market: 0,
      price_per_sqft: 20,
      sales_tax: 30,
    },
  },

  "Wellness Seeker": {
    description: "Clean air, long lives, sunshine, hikes. Health beats hustle.",
    weights: {
      life_expectancy: 100,
      air_quality_pm25: 100,
      uninsured_pct: 80,
      public_lands: 70,
      sunshine_hours: 60,
      disasters: 70,
      relative_humidity: 40,
      humidity: 40,
      precipitation: 30,
      avg_temperature: 30,
      feels_like_temperature: 30,
      cost_of_living: 40,
      median_age: 0,
      uv_index: 30,
      bachelors_pct: 30,
      median_income: 0,
      unemployment: 0,
      gun_friendliness: 0,
      income_tax: 0,
      sales_tax: 0,
      home_value: 0,
      median_rent: 0,
    },
  },

  "First-Time Buyer": {
    description: "Cheap entry-level homes, decent jobs, low closing-cost shock.",
    weights: {
      median_sale_price: 100,
      home_value: 90,
      price_per_sqft: 80,
      housing_inventory: 70,
      days_on_market: 50,
      cost_of_living: 80,
      home_insurance: 70,
      unemployment: 60,
      median_income: 40,
      median_rent: 40,
      income_tax: 50,
      sales_tax: 40,
      disasters: 60,
      population: 30,
      population_density: 30,
      broadband_pct: 40,
      commute_time: 30,
      bachelors_pct: 0,
      gun_friendliness: 0,
      humidity: 0,
      uv_index: 0,
      avg_temperature: 0,
      feels_like_temperature: 0,
      relative_humidity: 0,
      precipitation: 0,
      sunshine_hours: 0,
      public_lands: 0,
      life_expectancy: 30,
      air_quality_pm25: 0,
      uninsured_pct: 0,
      median_age: 0,
    },
  },
};
